# Generated by Django 4.2.7 on 2024-09-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_num",
            field=models.IntegerField(),
        ),
    ]
