# Generated by Django 4.2.7 on 2024-09-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_choice_choice_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choice_num",
            new_name="votes",
        ),
        migrations.AddField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
